
Length of test dataset: 8192
/Users/siemsj/projects/xlstm/experiments/eval.py:149: FutureWarning:
You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
Traceback (most recent call last):
  File "/Users/siemsj/miniconda3/envs/mother_gam/lib/python3.11/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/siemsj/miniconda3/envs/mother_gam/lib/python3.11/site-packages/matplotlib/__init__.py", line 866, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/siemsj/miniconda3/envs/mother_gam/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/siemsj/miniconda3/envs/mother_gam/lib/python3.11/site-packages/matplotlib/__init__.py", line 843, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/siemsj/projects/xlstm/experiments/eval.py", line 216, in <module>
    main(args.config, args.model, args.wandb_run_id)
  File "/Users/siemsj/projects/xlstm/experiments/eval.py", line 178, in main
    fig = create_improved_plots(sequence_lengths, sequence_accuracies, cfg.model.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/siemsj/projects/xlstm/experiments/eval.py", line 75, in create_improved_plots
    plt.style.use('seaborn')
  File "/Users/siemsj/miniconda3/envs/mother_gam/lib/python3.11/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
Test Loss: 0.4116
Test Accuracy: 0.8606